rive-app/rive-react

- README.md
This still needs to point to the updated `rive-js`, so I'm opening it in draft for now until that's merged and revved.
> Update README with camelCase params

- package.json
Something went wrong with deployment due to wrong npm token
> chore: bump to 0.0.12

- src/hooks/useRive.tsx
Canvas by default is an inline element, and 4px are added under it between it and the div container. When a resize happens, we take the size of the outer div and apply it to the canvas so it also resizes. This works fine when the width/height is static (e.g 500px) but not when it's dynamic (e.g 100%), as the extra 4px is taken in to account each time. To prevent this extra 4px, you need to make the canvas element `display: 'block'` or `verticalAlign: 'top'`.  I've gone with `verticalAlign: 'top'`.
https://stackoverflow.com/questions/8600393/there-is-a-4px-gap-below-canvas-video-audio-elements-in-html5
> Add verticalAlign = top to canvas to prevent canvas growth on resize

- .github/workflows/publish.yml
- README.md
- package.json
- setupTests.ts
- src/components/Rive.tsx
- src/hooks/useRive.tsx
- src/hooks/useStateMachineInput.ts
- src/index.ts
- src/types.ts
- test/useRive.test.tsx
Switching this runtime to use the `webgl`-backing runtime instead of `canvas` so we can allow React to support newer features (like Mesh). Once this is merged, we'll do a manual `release-it` run to bump to a major.
Taking out the npm publish business from our workflow as this will eventually be handled by a new publish shell script we'll run to coordinate a publish of the main package, and the derivatives (`rive-react-canvas` and `rive-react-webgl`) after this.
> Breaking: Switch from using the canvas renderer as default to the webgl renderer

- package.json
Go back to patch releases - and bump WebGL which should have @luigi-rosso fix for alignment 🙌
> Chore: Bump webgl and remove major flag from release-it command

- package.json
Taking a downstream wasm/js fix
> Patch: Bump rive-cpp to fix DAG issue

- README.md
- src/hooks/useStateMachineInput.ts
- test/useStateMachine.test.tsx
Wasn't a super straightforward way to set an initial value on a state machine input when its loaded in. This should provide a simpler way to set one.
Also added tests for the `useStateMachineInput` hook.
> Feat: Add extra param to useStateMachineInput to set an initial value on the input when its loaded

- package.json
Looking thru the [React changelog](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html) for supporting v18+, there should be no major changes needed here. Did some smoke tests thru some of our examples in the `examples` folder
Related to #73
> Maint: Allow peer dep React to use v18.0+

- .github/workflows/publish.yml
- README.md
- npm/react-canvas/README.md
- npm/react-webgl/README.md
- npm/rive-react-canvas/README.md
- npm/rive-react-webgl/README.md
- package.json
- scripts/build.sh
- scripts/bump_all_versions.sh
- scripts/bump_version.sh
- scripts/nextVersion.js
- scripts/publish_all.sh
- scripts/setup_all_packages.sh
- scripts/setup_package.sh
- scripts/trimPackageJson.js
- src/components/Rive.tsx
- src/hooks/useRive.tsx
- src/hooks/useStateMachineInput.ts
- src/index.ts
- src/types.ts
- test/useRive.test.tsx
- test/useStateMachine.test.tsx
Today, the React runtime wraps around only one dependency, either canvas or WebGL, and we wrap around WebGL currently since v1.0.0. However, we'll want to support both a canvas and WebGL renderer to be able to iterate on performance and developer experience through React. To do that, we'll want to do a similar strategy to the `rive-js` old dependency, and split into `@rive-app/react-canvas` and `@rive-app/react-webgl`. These scripts should help get us there. Below is an explanation on the strategy we can run through Github Actions.
Not running these scripts yet in GH action workflows for this PR, just want to get some feedback early here on the strategy and merge the scripts early if we go this route. The thinking is:
With the assumption:
- `rive-react` will have `@rive-app/canvas` and …
> Update: Adding build scripts to prepare for split of rive-react into 2 package derivatives for canvas and webgl

- README.md
- src/components/Rive.tsx
- src/hooks/useRive.tsx
- src/types.ts
- test/Rive.test.tsx
- test/useRive.test.tsx
Related to #6 .
We'll extract `className` and `style` out of any props from RiveComponent, then spread the rest onto the `canvas`.
> Breaking: Spread non-style props onto canvas element instead of containing div

- src/hooks/useRive.tsx
- test/useRive.test.tsx
Due to recent change where a change in animations names would update the playing animation. This would cause the animation to always play, even if autoplay was false.
> Fix animation playing with autoplay false when animation name passed

- package.json
Our `npm run build` script was failing in GH actions - after some more inspection, it looks like the `bunchee` tool we use to build released a new patch version (1.8.4) that seems to have some syntax issues that prevents building.
For now, I'm tie-ing the bunchee dep to the last working version I tested locally (one patch back)
> Fix: A recent Bunchee patch version kind of breaks npm run build

- CONTRIBUTING.md
- README.md
Condensing the docs down to point everything to help center. Really cuts down on redundancy of documentation in Github, keeps everything in one source of truth, and we separate concerns of README vs CONTRIBUTING docs.
> Docs: Condense down README and add CONTRIBUTING guide

- src/hooks/useRive.tsx
- test/useRive.test.tsx
This is to address the occasional time that we get a small Rive canvas that then quickly resolves into the appropriate container size. I'm not sure this entirely fixes it, so I'm open to other observations here if I'm missing the point of the problem.
> fix: make a canvas of size 0 until we calculate the bounds appropriately

- src/hooks/useRive.tsx
- src/utils.ts
- test/useRive.test.tsx
Adding a watcher on the `devicePixelRatio` to adjust the canvas dimensions properly. This might help fix issues we're seeing with rive-react in Framer code components where output can be blurry at times (not consistent and not replicable on all devices).
> fix: Adjust canvas size if devicePixelRatio changes for any reason

- package.json
- src/hooks/useRive.tsx
- test/useRive.test.tsx
Also call cleanup if we detect the component unmounted after we initialise it
Depends on updating dependencies once https://github.com/rive-app/rive-wasm/pull/271 goes in
> Call cleanup on unmount

- src/utils.ts
we found this bug in safari 13, we couldnt see any animation
that was coused by `addEventListener` in `matchMedia`
> Fix: matchMedia add event listener for safari 13 and older versions

- package.json
- src/components/Rive.tsx
This bump enables folks to pass in `shouldDisableRiveListeners: true` when using either `useRive` or the main `<Rive />` component, which will not set any event listeners on the canvas (also tries to detect this anyways at the WASM level, but this adds the option).
> patch: bump rive-wasm to allow new parameter for disabling Rive listeners

- examples/stories/RiveOverview.stories.mdx
- src/components/Rive.tsx
- src/hooks/useRive.tsx
- test/Rive.test.tsx
Small change to allow for setting children/fallback content inside the canvas when the canvas cannot be shown for certain users/browsers
> feat: allow for children to be set inside the canvas for fallback content when canvas cannot be shown

- package.json
Patching for a leak detected in rive-cpp
> chore: bump rive-wasm to 2.1.2

- package.json
Follow path constraint fix for nested artboards
> chore: bump rive-wasm to 2.1.5 for follow path fix

- package.json
Add support for out of band assets
> chore: bump react to 4.5.0

- package.json
- src/hooks/useDevicePixelRatio.ts
- src/hooks/useResizeCanvas.ts
- src/types.ts
- test/useRive.test.tsx
WASM recently had a param addition to the `resizeDrawingSurfaceToCanvas()` API to explicitly set a number for the dpr when calculating canvas area size. Introducing that here as an option in `useRive()`
> feat: add customDevicePixelRatio param from WASM for adjusting canvas size based on dpr

- package.json
Bumps WASM for low-level specific features, and added dependencies on the WASM build.
> chore: bump rive-wasm dependency to 2.10.0

- src/hooks/useResizeCanvas.ts
- src/hooks/useRive.tsx
- test/useRive.test.tsx
fixes #255 
this PR changes some parts of our hooks lifecycle to reload an animation if it has been previously destroyed.
> change hooks lifecycle to account for component reloading

- src/hooks/elementObserver.ts
- src/hooks/useIntersectionObserver.ts
- src/hooks/useRive.tsx
- src/types.ts
- test/elementObserver.test.tsx
- test/useIntersectionObserver.test.tsx
- test/useRive.test.tsx
this PR addresses three issues:
- fix for Chrome's issue with insertBefore and animations stopping
- add a new option "shouldUseIntersectionObserver" to allow users to opt-out of using the intersection observer
- uses a single instance of the intersection observer, because there is a big performance difference between using one per instance, and one for all elements.
> fix observer and use single instance

- src/hooks/useRiveFile.ts
- test/useRiveFile.test.tsx
This PR addresses [the issue](https://github.com/rive-app/rive-react/issues/267) with the `useRiveFile` hook not properly catching `RiveFile` initialization errors.
> fix: catch RiveFile initialization error in hook

- src/hooks/useStateMachineInput.ts
This PR addresses the issue where state machine inputs reset when `rive.play()` is called.
> fix: change initialization from play to load event

- npm/react-webgl2/package.json
- package.json
This PR addresses the issue with the `@rive-app/react-webgl2` package where imports from the underlying `@rive-app/webgl2` package are missing. 
For example, using this import statement: `import {decodeFont} from '@rive-app/react-webgl2';` would result in this error: `Module '"@rive-app/react-webgl2"' has no exported member 'decodeFont'.`
> fix: add webgl2 package to dependencies

- src/hooks/useRive.tsx
React ended up needing a few extra things. I thought it used `resizeDrawingSurfaceToCanvas` and not `resizeToCanvas`.
This can be cleaned up more as we need some properties from JS. Later we would also need to test a few more scenarios to make sure this always works as intended.
> fix: additional layout configuration that react needs

- src/hooks/useRive.tsx
in a scenario where the instance was not loaded yet and the useEffect would run again, we were not cleaning up the instance causing memory leaks because elements were not being deleted.
> cleanup instance if use effect reruns and instance is not loaded
